"""Run the leakage-safe CS2 roster-change causal study.

Usage from the repository root:
    .venv/Scripts/python.exe scripts/run_causal_roster_study.py

The pipeline requires the existing cleaned series table and raw lineup data.
It never downloads data and writes only derived files under outputs/ and reports/.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from cs2analytics.causal import (
    balance_table,
    bootstrap_did,
    build_event_windows,
    build_paired_event_panel,
    build_team_match_panel,
    did_estimate,
    event_study_table,
    nearest_control_matches,
)

REPO = Path(__file__).resolve().parents[1]
LINEUP_COLUMNS = [f"team{s}_player{i}_id" for s in (1, 2) for i in range(1, 6)]


def load_inputs(series_path: Path, raw_path: Path) -> pd.DataFrame:
    """Join one series row to the first available real lineup observation."""
    series = pd.read_csv(series_path)
    series["datetime"] = pd.to_datetime(series["datetime"], utc=True, errors="raise")
    raw_columns = ["match_id", "is_total", *LINEUP_COLUMNS]
    raw = pd.read_csv(raw_path, usecols=raw_columns, low_memory=False)
    raw = raw.sort_values(["match_id", "is_total"], kind="mergesort")
    # Map rows are preferred because they carry real per-map lineups; summary
    # rows remain a fallback for newer summary-only records.
    lineups = raw.groupby("match_id", as_index=False).first()[["match_id", *LINEUP_COLUMNS]]
    merged = series.merge(lineups, on="match_id", how="left", validate="one_to_one")
    return merged


def _write_report(
    path: Path,
    *,
    series: pd.DataFrame,
    team_panel: pd.DataFrame,
    treated_windows: pd.DataFrame,
    pairs: pd.DataFrame,
    did: dict[str, float | int] | None,
    uncertainty: dict[str, float | int] | None,
    pretrend: dict[str, float | bool] | None,
) -> None:
    lines = [
        "# CS2 Roster-Change Causal Study",
        "",
        "Generated by `scripts/run_causal_roster_study.py`.",
        "",
        "## Cohort coverage",
        "",
        f"- Series rows: {len(series):,}",
        f"- Team-match rows: {len(team_panel):,}",
        f"- Treated event windows: "
        f"{treated_windows['event_id'].nunique() if not treated_windows.empty else 0}",
        f"- Matched event pairs: {len(pairs):,}",
        "",
        "## Estimand",
        "",
        "The baseline estimates the change in the treated team's outcome after a qualifying "
        "roster change, minus the change for a time-near, tier-matched untreated control "
        "event. This is a descriptive DiD baseline, not proof that matching removed "
        "unobserved confounding.",
        "",
        "## DiD result",
        "",
    ]
    if did is None:
        lines.append("No complete matched panel was available; no DiD estimate was produced.")
    else:
        lines.extend(
            [
                f"- Treated pre/post: {did['treated_pre']:.4f} → {did['treated_post']:.4f}",
                f"- Control pre/post: {did['control_pre']:.4f} → {did['control_post']:.4f}",
                f"- DiD estimate: **{did['estimate']:.4f}**",
                (
                    f"- Cluster bootstrap 95% interval: "
                    f"[{uncertainty['ci_low']:.4f}, {uncertainty['ci_high']:.4f}]"
                    if uncertainty is not None
                    else "- Cluster bootstrap interval: unavailable"
                ),
                f"- Team-match observations: treated {did['n_treated']}, "
                f"control {did['n_control']}",
            ]
        )
        if pretrend is not None:
            lines.extend(
                [
                    "",
                    "## Pre-trend screen",
                    "",
                    f"- Lead at relative match -1: {pretrend['lead_minus_one']:.4f}",
                    f"- Maximum absolute pre-treatment lead difference: "
                    f"{pretrend['max_abs_lead_difference']:.4f}",
                    "- **Warning: the simple parallel-trends screen fails.** Treat the DiD "
                    "number as a diagnostic, not a publishable causal effect."
                    if not pretrend["passes_screen"]
                    else "- No large lead difference crossed the provisional 0.10 screen.",
                ]
            )
    lines.extend(
        [
            "",
            "## Required interpretation checks",
            "",
            "- Inspect `causal_event_study.csv` for pre-treatment lead differences.",
            "- Inspect `causal_balance.csv`; large standardized mean differences "
            "indicate poor comparability.",
            "- Treat estimates as unsupported if overlap is poor or placebo/pre-trend checks fail.",
            "- Do not use the result as betting advice or as an evaluation of individual players.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--series", type=Path, default=REPO / "outputs" / "series_clean.csv")
    parser.add_argument(
        "--raw", type=Path, default=REPO / "data" / "raw" / "cs2_all_tiers_games.csv"
    )
    parser.add_argument("--outdir", type=Path, default=REPO / "outputs")
    parser.add_argument("--pre-window", type=int, default=5)
    parser.add_argument("--post-window", type=int, default=5)
    args = parser.parse_args()

    for path in (args.series, args.raw):
        if not path.exists():
            parser.error(f"missing input: {path}")

    series = load_inputs(args.series, args.raw)
    team_panel = build_team_match_panel(series)
    treated_windows = build_event_windows(
        team_panel,
        pre_window=args.pre_window,
        post_window=args.post_window,
        min_pre_stable=3,
        max_post_changes=0,
    )
    pairs = nearest_control_matches(
        team_panel,
        treated_windows,
        covariates=["pre_stable_matches"],
        max_date_days=90,
        pre_window=args.pre_window,
        post_window=args.post_window,
    )
    paired = build_paired_event_panel(
        team_panel,
        treated_windows,
        pairs,
        pre_window=args.pre_window,
        post_window=args.post_window,
    )

    args.outdir.mkdir(parents=True, exist_ok=True)
    reports = REPO / "reports"
    reports.mkdir(exist_ok=True)
    treated_windows.to_csv(args.outdir / "causal_treated_windows.csv", index=False)
    pairs.to_csv(args.outdir / "causal_event_pairs.csv", index=False)

    did: dict[str, float | int] | None = None
    uncertainty: dict[str, float | int] | None = None
    pretrend: dict[str, float | bool] | None = None
    if not paired.empty:
        did = did_estimate(paired, outcome="win")
        uncertainty = bootstrap_did(paired, outcome="win", n_boot=2000, seed=20260921)
        event_study = event_study_table(paired, outcome="win")
        event_study.to_csv(args.outdir / "causal_event_study.csv", index=False)
        leads = event_study[event_study["relative_match"] < 0]["difference"]
        lead_minus_one = event_study.loc[
            event_study["relative_match"] == -1, "difference"
        ]
        pretrend = {
            "lead_minus_one": (
                float(lead_minus_one.iloc[0]) if not lead_minus_one.empty else float("nan")
            ),
            "max_abs_lead_difference": (
                float(leads.abs().max()) if not leads.empty else float("nan")
            ),
            "passes_screen": bool(not leads.empty and leads.abs().max() <= 0.10),
        }
        points = paired[paired["relative_match"] == 0].copy()
        balance_table(points, ["pre_stable_matches", "change_count"]).to_csv(
            args.outdir / "causal_balance.csv", index=False
        )
    else:
        pd.DataFrame().to_csv(args.outdir / "causal_event_study.csv", index=False)
        pd.DataFrame().to_csv(args.outdir / "causal_balance.csv", index=False)

    with (args.outdir / "causal_did.json").open("w", encoding="utf-8") as handle:
        json.dump(
            {"did": did, "bootstrap": uncertainty, "pretrend": pretrend},
            handle,
            indent=2,
            allow_nan=False,
        )
    _write_report(
        reports / "roster-causal-study.md",
        series=series,
        team_panel=team_panel,
        treated_windows=treated_windows,
        pairs=pairs,
        did=did,
        uncertainty=uncertainty,
        pretrend=pretrend,
    )
    print(
        f"series={len(series):,} team_matches={len(team_panel):,} "
        f"events={treated_windows['event_id'].nunique() if not treated_windows.empty else 0} "
        f"pairs={len(pairs):,} paired_rows={len(paired):,}"
    )
    if did is not None:
        assert uncertainty is not None
        print(
            f"did_win={did['estimate']:.6f} "
            f"ci95=[{uncertainty['ci_low']:.6f}, {uncertainty['ci_high']:.6f}]"
        )
    else:
        print("did_win=not-estimated (no complete matched panel)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
